module Irasutoya
  class Irasuto
    include Modules::HasDocumentFetcher::Methods
    include Modules::HasListPageParser::Methods
    include Modules::HasShowPageParser::Methods
    extend Modules::HasDocumentFetcher::Methods
    extend Modules::HasListPageParser::Methods
    extend Modules::HasShowPageParser::Methods

    attr_reader url: String
    attr_reader title: String
    attr_reader description: String
    attr_reader image_urls: Array[String]
    attr_reader postthumb_image_url: String?
    attr_reader image_url: String?
    attr_reader has_multiple_images: bool

    def initialize: (url: String, title: String, description: String, image_urls: Array[String]) -> void
    def self.random: -> Irasuto
    def self.search: (query: String, ?page: Integer) -> Array[IrasutoLink]
    def self.random_api_path: -> String
    def self.random_url: -> String
  end
end
