module Irasutoya
  module Modules
    module HasShowPageParser
      def self.included: (Class) -> void

      module Methods
        def parse_show_page: (document: untyped) -> { title: String, description: String, image_urls: Array[String] }
      end

      module PrivateMethods
        def self.title_from: (document: untyped) -> String
        def self.description_from: (document: untyped) -> String
        def self.image_url_from: (document: untyped) -> String
        def self.image_urls_from: (document: untyped) -> Array[String]
      end
    end
  end
end
